version: "3.3"

services:
  expo_app:
    container_name: expo_app
    build: .
    ports:
      - 19000:19003
      - 19001:19007
      - 19002:19008
      - 19006:19009
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/home
